sudo: false

language: java

before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.png)|(.pdf)|(.html)|^(LICENSE)|^(docs)'
    then
      echo "Only doc files were updated, not running the CI."
      exit
    fi

script:
  - mvn clean install -U -B -q

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && mvn package -DskipTests && mvn docker:build && mvn docker:push
  on:
    branch: master